#ifndef ERRORS_H
#define ERRORS_H

enum error {
  ERR_SUCCESS,
  ERR_PTRACE_ATTACH,
  ERR_PTRACE_SETOPTIONS_TRACESYSGOOD,
  ERR_PTRACE_SETOPTIONS_TRACECLONE,
  ERR_PTRACE_SYSCALL,
  ERR_PTRACE_GETREGS,
  ERR_PTRACE_PEEKTEXT,
  ERR_TERMINATED,
  ERR_STOPPED,
  ERR_WAITPID,
  ERR_ILLEGAL_DEREF,
  ERR_OPEN_TDF,
  ERR_INVALID_FILEFORMAT,
  ERR_FAILED_TO_READ_TDF,
  ERR_MALLOC,
  ERR_NOARGS,
  ERR_INVALID_PID
};

#endif
